CREATE TYPE "perfil_usuario" AS ENUM (
  'host',
  'cliente'
);

CREATE TYPE "status_reserva" AS ENUM (
  'pendente',
  'aguardando_pagamento',
  'confirmada',
  'cancelada',
  'concluida'
);

CREATE TABLE "usuarios" (
  "id" uuid PRIMARY KEY,
  "nome" varchar(150) NOT NULL,
  "perfil" perfil_usuario NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "telefone" varchar(20),
  "data_nascimento" date,
  "senha_hash" varchar(255) NOT NULL,
  "foto_perfil" varchar(500),
  "criado_em" timestamp,
  "atualizado_em" timestamp
);

CREATE TABLE "tipos_espaco" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "enderecos" (
  "id" uuid PRIMARY KEY,
  "cep" varchar(10),
  "logradouro" varchar(255),
  "numero" varchar(20),
  "complemento" varchar(100),
  "bairro" varchar(100),
  "cidade" varchar(100),
  "estado" varchar(2),
  "pais" varchar(100),
  "latitude" decimal(10,8),
  "longitude" decimal(11,8)
);

CREATE TABLE "espacos" (
  "id" uuid PRIMARY KEY,
  "host_id" uuid NOT NULL,
  "endereco_id" uuid NOT NULL,
  "tipo_id" int NOT NULL,
  "titulo" varchar(255) NOT NULL,
  "descricao" text,
  "capacidade" int NOT NULL,
  "preco_diaria" decimal(10,2) NOT NULL,
  "horario_checkin" time,
  "horario_checkout" time,
  "ativo" boolean DEFAULT true,
  "criado_em" timestamp,
  "atualizado_em" timestamp
);

CREATE TABLE "fotos_espaco" (
  "id" uuid PRIMARY KEY,
  "espaco_id" uuid NOT NULL,
  "url" varchar(500) NOT NULL,
  "principal" boolean DEFAULT false,
  "ordem" int DEFAULT 0,
  "criado_em" timestamp
);

CREATE TABLE "comodidades" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) UNIQUE NOT NULL,
  "icone" varchar(50)
);

CREATE TABLE "espaco_comodidade" (
  "espaco_id" uuid NOT NULL,
  "comodidade_id" int NOT NULL,
  PRIMARY KEY ("espaco_id", "comodidade_id")
);

CREATE TABLE "reservas" (
  "id" uuid PRIMARY KEY,
  "espaco_id" uuid NOT NULL,
  "cliente_id" uuid NOT NULL,
  "inicio" timestamp NOT NULL,
  "fim" timestamp NOT NULL,
  "quantidade_pessoas" int NOT NULL,
  "valor_diaria" decimal(10,2) NOT NULL,
  "taxa_servico" decimal(10,2) DEFAULT 0,
  "valor_total" decimal(10,2) NOT NULL,
  "status" status_reserva NOT NULL,
  "criado_em" timestamp,
  "atualizado_em" timestamp
);

CREATE TABLE "avaliacoes" (
  "id" uuid PRIMARY KEY,
  "reserva_id" uuid UNIQUE NOT NULL,
  "cliente_id" uuid NOT NULL,
  "host_id" uuid NOT NULL,
  "espaco_id" uuid NOT NULL,
  "nota" int NOT NULL,
  "comentario" text,
  "criado_em" timestamp
);

CREATE TABLE "bloqueios" (
  "id" uuid PRIMARY KEY,
  "espaco_id" uuid NOT NULL,
  "inicio" timestamp NOT NULL,
  "fim" timestamp NOT NULL,
  "motivo" varchar(100),
  "criado_em" timestamp
);

CREATE TABLE "favoritos" (
  "usuario_id" uuid NOT NULL,
  "espaco_id" uuid NOT NULL,
  "criado_em" timestamp,
  PRIMARY KEY ("usuario_id", "espaco_id")
);

ALTER TABLE "espacos" ADD FOREIGN KEY ("host_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "espacos" ADD FOREIGN KEY ("endereco_id") REFERENCES "enderecos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "espacos" ADD FOREIGN KEY ("tipo_id") REFERENCES "tipos_espaco" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fotos_espaco" ADD FOREIGN KEY ("espaco_id") REFERENCES "espacos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "espaco_comodidade" ADD FOREIGN KEY ("espaco_id") REFERENCES "espacos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "espaco_comodidade" ADD FOREIGN KEY ("comodidade_id") REFERENCES "comodidades" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservas" ADD FOREIGN KEY ("espaco_id") REFERENCES "espacos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservas" ADD FOREIGN KEY ("cliente_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "avaliacoes" ADD FOREIGN KEY ("reserva_id") REFERENCES "reservas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "avaliacoes" ADD FOREIGN KEY ("cliente_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "avaliacoes" ADD FOREIGN KEY ("host_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "avaliacoes" ADD FOREIGN KEY ("espaco_id") REFERENCES "espacos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bloqueios" ADD FOREIGN KEY ("espaco_id") REFERENCES "espacos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favoritos" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favoritos" ADD FOREIGN KEY ("espaco_id") REFERENCES "espacos" ("id") DEFERRABLE INITIALLY IMMEDIATE;
